[package]
name = "cairo_vm"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "cairo_vm"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
bincode = "2.0.0-rc.3"
juvix-cairo-vm = { git = "https://github.com/anoma/juvix-cairo-vm"}
serde_json = "1.0.120"
