name: Pull request checks

on:
  pull_request:
    branches: [ "base" ]

permissions:
  contents: read

jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        revision: ['topic']
    name: Tests, dialyzer, format
    runs-on: ubuntu-latest
    steps:
    - name: Check out topic
      uses: actions/checkout@v4.1.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - uses: ./.github/workflows/setup
      if: steps.try_merge.outcome != 'failure'
      with:
        fail-on-failure: false

    - uses: ./.github/workflows/checks
      if: steps.try_merge.outcome != 'failure'


    - uses: ./.github/workflows/format
      if: ${{ !cancelled() && steps.try_merge.outcome != 'failure' }}
